config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'transactions#index'

  post 'authenticate', to: 'authentication#authenticate'
  resources :merchants
  resources :transactions, only: [:index, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  include ActiveModel::Validations

  belongs_to :user
  belongs_to :parent_transaction, class_name: 'Transaction', foreign_key: 'transaction_id', optional: true
  has_one :child_transaction, class_name: 'Transaction', foreign_key: 'transaction_id',
                              dependent: :restrict_with_exception

  STATUSES = {
    approved: 0,
    reversed: 1,
    refunded: 2,
    error: 3
  }.freeze

  CORRECT_PARENT_STATUSES = [
    STATUSES[:approved],
    STATUSES[:refunded]
  ].freeze

  enum status: STATUSES

  validates_with UuidValidator
  validates_with TransactionStatusValidator
  validates_with TransactionMerchantStatusValidator
  validates_with TransactionParentValidator
  validates :customer_email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :status, inclusion: { in: STATUSES.keys.map(&:to_s) }
  validates :type,
            inclusion: { in: %w[Transaction::Authorize Transaction::Charge Transaction::Refund Transaction::Reversal] }

  scope :obsolete, -> { where('created_at < ?', Time.current - 1.hour) }
end

app/models/transaction/authorize.rb
# frozen_string_literal: true

class Transaction::Authorize < Transaction
end

app/models/transaction/charge.rb
# frozen_string_literal: true

class Transaction::Charge < Transaction
  ALLOWED_PARENT = 'Transaction::Authorize'
end

app/models/transaction/refund.rb
# frozen_string_literal: true

class Transaction::Refund < Transaction
  ALLOWED_PARENT = 'Transaction::Charge'
end

app/models/transaction/reversal.rb
# frozen_string_literal: true

class Transaction::Reversal < Transaction
  ALLOWED_PARENT = 'Transaction::Authorize'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :transactions, dependent: :restrict_with_exception

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/user/admin.rb
# frozen_string_literal: true

class User::Admin < User
end

app/models/user/merchant.rb
# frozen_string_literal: true

class User::Merchant < User
  STATUSES = {
    active: 0,
    inactive: 1
  }.freeze

  scope :active, -> { where(status: STATUSES[:active]) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  attr_reader :current_user

  private

  def authenticate_request
    @current_user = AuthorizeApiRequest.call(request.headers).result
    return if @current_user

    respond_to do |format|
      format.json do
        render json: { error: 'Not Authorized' }, status: 401
      end
      format.xml do
        render xml: '<error>Not Authorized</error>', status: 401
      end
    end
  end
end

app/controllers/authentication_controller.rb
# frozen_string_literal: true

class AuthenticationController < ApplicationController
  # skip_before_action :authenticate_request
  protect_from_forgery with: :null_session

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])

    if command
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
  before_action :merchant, except: %i[index new create]

  def index
    @merchants = User::Merchant.all
  end

  def show; end

  def new; end

  def edit; end

  def update
    if merchant.update(merchant_params)
      redirect_to root_path, notice: 'Updated Successfully!'
    else
      flash.now.alert = merchant.errors.full_messages
      render :edit
    end
  end

  def create
    @new_merchant = User::Merchant.new(merchant_params)
    if @new_merchant.save
      redirect_to root_path, notice: 'Created Successfully!'
    else
      flash.alert = @new_merchant.errors.full_messages
      redirect_back(fallback_location: merchants_path)
    end
  end

  def destroy
    merchant.destroy
    redirect_to root_path
  end

  private

  def merchant_params
    params.require(:user_merchant).permit(:name, :email, :password, :description)
  end

  def merchant
    @merchant ||= User::Merchant.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  include TransactionsHelper

  before_action :authenticate_request, only: :create
  protect_from_forgery with: :null_session

  def create
    respond_to do |format|
      format.json do
        new_transaction = TransactionCreator.call(params, :json)
        render_response(new_transaction, :json)
      end
      format.xml do
        new_transaction = TransactionCreator.call(params, :xml)
        render_response(new_transaction, :xml)
      end
    end
  end

  def index
    @transactions = Transaction.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def display_messages(messages)
    return messages if messages.is_a?(String)

    messages.join('; ')
  end
end

app/helpers/merchants_helper.rb
# frozen_string_literal: true

module MerchantsHelper
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
  def render_response(transaction, format)
    case format
    when :json
      render_json_response(transaction)
    when :xml
      render_xml_response(transaction)
    end
  end

  def render_json_response(transaction)
    if transaction.persisted?
      render json: { transaction: }
    else
      render json: { errors: transaction.errors.messages }, status: 422
    end
  end

  def render_xml_response(transaction)
    if transaction.persisted?
      render xml: transaction.attributes.to_xml(root: 'transaction')
    else
      render xml: transaction.errors.messages.to_xml(root: 'transaction'), status: 422
    end
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    title MerchantTest
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="turbo-visit-control" content="reload"
    == csrf_meta_tags
    == csp_meta_tag

    == stylesheet_link_tag "application", "data-turbo-track": "reload"
    == javascript_importmap_tags

    body
    .container
      div class="row justify-content-center"
      == link_to 'Merchants', merchants_path
      == link_to 'Transactions', root_path
      == render 'shared/flashes'
      == yield

app/views/merchants/edit.slim
h4 class="mt-4 mb-4 display-4"
  Edit Merchant
== form_with(model: @merchant, url: merchant_path, method: :put, local: true, data: { turbo: false }) do |form|
  div class="form-group"
    == form.label :name
    == form.text_field :name, class: 'form-control'
  div class="form-group"
    == form.label :email
    == form.text_field :email, class: 'form-control'
  div class="form-group"
    == form.label :password
    == form.password_field :password, class: 'form-control'
  div class="form-group"
    == form.label :description
    == form.text_area :description, class: 'form-control'
  div class="form-group"
    == form.submit class: 'form-control btn-primary'

app/views/merchants/index.slim
h4 class="mt-4 display-4"
  'Merchants List
== link_to 'Create Merchant', new_merchant_path
- if @merchants.present?
  table class="table table-bordered"
    thead
      tr
        th scope="col" Name
        th scope="col" Email
        th scope="col" Description
        th scope="col" colspan="3" Action
    tbody
      - @merchants.each do |merchant|
        tr
          td == merchant.name
          td == merchant.email
          td == merchant.description
          td == link_to 'Show', merchant_path(merchant.id)
          td == link_to 'Edit', edit_merchant_path(merchant.id)
          td
            == link_to 'Delete',
            merchant_path(merchant.id),
            data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
- else
  div class="p-3 mb-2 bg-light text-dark"
    span class="text-info font-weight-bold"
      'Welcome!
    'Create first Merchant

app/views/merchants/new.slim
h4 class="mt-4 mb-4 display-4"
  New Merchant
== form_with model: @new_merchant, scope: :user_merchant, url: merchants_path, local: true, data: { turbo: false } do |form|
  div class="form-group"
    == form.label :name
    == form.text_field :name, class: 'form-control'
  div class="form-group"
    == form.label :email
    == form.text_field :email, class: 'form-control'
  div class="form-group"
    == form.label :password
    == form.password_field :password, class: 'form-control'
  div class="form-group"
    == form.label :description
    == form.text_area :description, class: 'form-control'

  div class="form-group"
    == form.submit class: 'form-control btn-primary'

app/views/merchants/show.slim
h4 class="mt-4 mb-4 display-4"
  'Show details of Merchant
  == @merchant.id
table class="table"
  tbody
    tr
      th Name:
      td == @merchant.name
    tr
      th Email:
      td == @merchant.email
    tr
      th Description:
      td == @merchant.description

app/views/shared/_flashes.slim
- if flash.any?
  - flash.each do |type, msg|
    div class="alert alert-#{type} alert-dismissible fade show m-1" role="alert"
      == display_messages(msg)

app/views/transactions/index.slim
h4 class="mt-4 display-4"
  'Transactions List
- if @transactions.present?
    table class="table table-bordered"
      thead
        tr
          th scope="col" UUID
          th scope="col" Customer Email
          th scope="col" Customer Phone
          th scope="col" Amount
          th scope="col" Type
          th scope="col" Status
          th scope="col" User ID
          th scope="col" Parent Transaction ID
          th scope="col" Created At
      tbody
        - @transactions.each do |transaction|
          tr
            td == transaction.uuid
            td == transaction.customer_email
            td == transaction.customer_phone
            td == transaction.amount
            td == transaction.type
            td == transaction.status
            td == transaction.user.id
            td == transaction.transaction_id
            td == transaction.created_at
- else
  div class="p-3 mb-2 bg-light text-dark"
    span class="text-info font-weight-bold"
      'Welcome!
    'There are no transactions yet.